spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://127.0.0.1:3306/netpod?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
            username: root
            password: 
            initial-size: 10
            max-active: 1000
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #Oracle需要打开注释
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true

# 图片、视频路径
uploadFilePath: /usr/local/ops/uploadfile/maibox/
thumbFilePath: /usr/local/ops/uploadfile/thumb/
videoCutFilePath: /usr/local/ops/uploadfile/videoCut/

# zabbix
zabbixUrl: http://127.0.0.1:8080/zabbix/api_jsonrpc.php
zabbixUserName: Admin
zabbixPassWord: zabbix

 # 日志目录
logging:
    file:
        path: /usr/local/ops/logs/
